# Generated by Django 2.0.2 on 2018-02-27 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_name', models.TextField(max_length=100)),
                ('user_favorite_count', models.IntegerField()),
                ('user_friends_count', models.IntegerField()),
                ('user_followers_count', models.IntegerField()),
                ('screen_name', models.TextField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('quote_count', models.IntegerField()),
                ('reply_count', models.IntegerField()),
                ('retweet_count', models.IntegerField()),
                ('favorite_count', models.IntegerField()),
                ('hash_tags', models.TextField(default='', max_length=1000)),
                ('user_mentions', models.TextField(default='', max_length=1000)),
            ],
        ),
    ]
