# Generated by Django 2.0.2 on 2018-02-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_api', '0002_tweetinfo_hash_tags_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetinfo',
            name='user_mentions_count',
            field=models.IntegerField(default=0),
        ),
    ]
